// src/data/filters.js

export const filterData = {
  lande: ["spanien", "italien", "østrig", "frankrig", "portugal", "grækenland", "danmark", "tyskland", "georgia", "georgien", "slovenien", "australien", "hungary", "greece", "germany", "slovakia", "slovakiet", "ungarn", "australia", "argentina", "tjekkiet"],
  typer: ["hvid", "hvidvin", "red wine", "rødvin", "Magnum", "orangevin", "cider", "rød", "rosé", "bobbler", "rose", "Rosevin", "pet nat", "sparkling wine", "orange", "orange wine", "white wine", "mineral white wine", "lav alkohol", "Orangevin", "bubbles", "0%"],
  producent: [
    "Frédéric Cossard",
    "Drudgaard Vin",
    "Domaine la Grapp'A",
    "9+",
    "Momento Mori",
    "Radikon",
    "Judith Beck",
    "La Franchaie",
    "Andi Weigand",
    "Sete",
    "Anders Frederik Steen",
    "Patrick Desplats",
    "La Dernière Goutte",
    "Raphaëlle Guyot",
    "Dosnon",
    "Saint Pierre",
    "Staffelter-Hof",
    "Marinho",
    "Olivier Boulin",
    "Chapuis & Chapuis",
    "Vin des Potes",
    "Cantina Ortaccio",
    "Maison Crochet",
    "Domaine Tissot",
    "Jérôme Arnoux",
    "Jean-Marc Dreyer",
    "Richard Stàvek",
    "Domaine de la Tournelle",
    "Jean-Claude Rateau",
    "Mas de Janiny",
    "Emelie Hurtubise / Raphaël Beysang",
    "Volatil",
    "Jean-Pierre Robinot",
    "Alexis Hudon",
    "Jerôme Saurigny",
    "Domaine Labet",
    "Noita Winery",
    "Julien Merle",
    "La Vigne du Perron",
    "Sense Pressa",
    "Château Khashmi",
    "Jean-Francois Ganevat",
    "Des Vins d'Envie",
    "Eric Pfifferling",
    "La Boheme",
    "Ariane Lesne",
    "Robb de Matt",
    "Jouveaux",
    "Yann Durieux",
    "Cristiano Guttarolo",
    "Vincent Tricot",
    "Matassa",
    "Andrea Calek",
    "Weingut Brand",
    "Sons of Wine",
    "Bourre Pif",
    "Yvon Metras",
    "Julien Meyer",
    "Cati Ribot",
    "Les Cavarodes",
    "Fabien Jouves",
    "Weingut Leiner",
    "Domaine du Temps",
    "Domaine du Petit Oratoire",
    "Philippe Bornard",
    "Domaine in Black",
    "Jean-Yves Péron",
    "Tanini",
    "Kolonia 52",
    "Lorenzo Raffaglio",
    "Romain des Grottes",
    "Ratapoil",
    "Clos Rougeard",
    "François Rousset-Martin",
    "Les Astronautes",
    "Milan Nestarec",
    "Du Vin aux Liens",
    "Jugo Vins",
    "Ivo Ferreira",
    "Bergkloster",
    "Julien Guillot",
    "Sistema Vinari",
    "Matunei",
    "Cascina Tavijn",
    "Mark Angeli",
    "Réka.koncz",
    "Ingenium",
    "Foradori",
    "Marco Barba",
    "Yannick Meckert",
    "Domaine Valette",
  ],
};
