// src/data/filters.js

export const filterData = {
  lande: ["argentina", "australia", "australien", "danmark", "frankrig", "georgia", "georgien", "germany", "greece", "grækenland", "hungary", "italien", "portugal", "slovakia", "slovakiet", "slovenien", "spanien", "tjekkiet", "tyskland", "ungarn", "østrig"],
  typer: ["0%", "bobbler", "cider", "hvidvin", "lav alkohol", "orangevin", "pet nat", "rosé", "rødvin"],
  producent: [
    "9+",
    "Alexis Hudon",
    "Andrea Calek",
    "Anders Frederik Steen",
    "Andi Weigand",
    "Ariane Lesne",
    "Bergkloster",
    "Bourre Pif",
    "Cantina Ortaccio",
    "Cascina Tavijn",
    "Cati Ribot",
    "Chapuis & Chapuis",
    "Château Khashmi",
    "Clos Rougeard",
    "Cristiano Guttarolo",
    "Des Vins d'Envie",
    "Domaine de la Tournelle",
    "Domaine du Petit Oratoire",
    "Domaine du Temps",
    "Domaine in Black",
    "Domaine la Grapp'A",
    "Domaine Labet",
    "Domaine Tissot",
    "Domaine Valette",
    "Dosnon",
    "Drudgaard Vin",
    "Du Vin aux Liens",
    "Emelie Hurtubise / Raphaël Beysang",
    "Eric Pfifferling",
    "Fabien Jouves",
    "Foradori",
    "François Rousset-Martin",
    "Frédéric Cossard",
    "Ingenium",
    "Ivo Ferreira",
    "Jean-Claude Rateau",
    "Jean-Francois Ganevat",
    "Jean-Marc Dreyer",
    "Jean-Pierre Robinot",
    "Jean-Yves Péron",
    "Jerôme Saurigny",
    "Judith Beck",
    "Julien Guillot",
    "Julien Merle",
    "Julien Meyer",
    "Jugo Vins",
    "Jouveaux",
    "Kolonia 52",
    "La Boheme",
    "La Dernière Goutte",
    "La Franchaie",
    "La Vigne du Perron",
    "Les Astronautes",
    "Les Cavarodes",
    "Lorenzo Raffaglio",
    "Marco Barba",
    "Marinho",
    "Mark Angeli",
    "Mas de Janiny",
    "Matassa",
    "Matunei",
    "Maison Crochet",
    "Milan Nestarec",
    "Momento Mori",
    "Noita Winery",
    "Olivier Boulin",
    "Patrick Desplats",
    "Philippe Bornard",
    "Radikon",
    "Raphaëlle Guyot",
    "Ratapoil",
    "Réka.koncz",
    "Richard Stàvek",
    "Robb de Matt",
    "Romain des Grottes",
    "Saint Pierre",
    "Sense Pressa",
    "Sete",
    "Sistema Vinari",
    "Sons of Wine",
    "Staffelter-Hof",
    "Tanini",
    "Vin des Potes",
    "Vincent Tricot",
    "Volatil",
    "Weingut Brand",
    "Weingut Leiner",
    "Yann Durieux",
    "Yannick Meckert",
    "Yvon Metras",
  ],
};
