import type { Metadata } from "next";
import "../styles/globals.css";
import { Abel } from "next/font/google";
import { Menu } from "@/components/Menu/Menu";

export const abel = Abel({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-abel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={abel.className}>
        {/* <Menu /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
